<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_D Gii</name>
   <tag></tag>
   <elementGuidId>5e540062-89a8-438c-95bb-53260f40ce2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b20fc8e-a740-4c72-a505-ed7a8dca23f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d315dff2-62bb-4660-8f72-93ff1df1b87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://truyenteen.me/the-loai/di-gioi</value>
      <webElementGuid>a46e89bc-87ad-479c-8c9c-8c091b42e734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dị Giới</value>
      <webElementGuid>f70b3084-3079-4931-b63c-9f294bad398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav m-auto&quot;]/li[@class=&quot;nav-item dropdown has-mega-menu mr-2&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;px-0 container container-md&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-md-4&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>dcef81a1-19b2-421a-9803-35509d37f6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/a[4]</value>
      <webElementGuid>f1770174-426e-4ea8-8120-f5b1ed505bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dị Giới')]</value>
      <webElementGuid>c5d2b10a-6f6b-4ab0-a8c2-435c6e11e6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cung Đấu'])[1]/following::a[1]</value>
      <webElementGuid>d3597829-20fb-4b33-b8f8-05fe05abc7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cổ Đại'])[1]/following::a[2]</value>
      <webElementGuid>e063b444-bc27-4653-8d60-3d2bb5839e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đam Mỹ'])[1]/preceding::a[1]</value>
      <webElementGuid>01429ac3-853e-4edc-aea4-b181f8c62b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điền Văn'])[1]/preceding::a[2]</value>
      <webElementGuid>5743d6f3-992c-4692-8f91-e4a7f0c14d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dị Giới']/parent::*</value>
      <webElementGuid>5b5dbc73-f1ea-4bd1-a71a-68271799cb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://truyenteen.me/the-loai/di-gioi')]</value>
      <webElementGuid>0aeda8eb-0dbd-4315-9a75-6a8278c66dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>e38ed664-64f7-41dc-8c17-527b4fff4197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://truyenteen.me/the-loai/di-gioi' and (text() = 'Dị Giới' or . = 'Dị Giới')]</value>
      <webElementGuid>94151ac9-1455-4bb0-8502-5eec57012f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
