<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__genre</name>
   <tag></tag>
   <elementGuidId>a6bca51a-7721-4344-94bc-5e653e170c19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genre_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genre_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4e99ec3-0c3a-4202-babe-81bbf1049244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8e34ec08-7aa2-47d2-b46d-fd0026396873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b2b401ef-4150-42e3-b24b-921cc9f33071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genre[]</value>
      <webElementGuid>a82cfe72-cbe3-41ef-9d65-ace918446aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genre_6</value>
      <webElementGuid>c086a9ea-d585-4de2-9734-67741eee1cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>24cea5dd-9eac-46d3-9b45-a83262ebd380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genre_6&quot;)</value>
      <webElementGuid>3468b1b0-177c-4e09-926a-d48a5b1a418c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genre_6']</value>
      <webElementGuid>409f2442-fe37-448b-874c-95d001457cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>48800968-4346-40e2-b4b0-e7233e6d5475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'genre[]' and @id = 'genre_6']</value>
      <webElementGuid>d0127b5d-01db-4790-a379-01a4a5e41b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
