<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bch Hp_genre</name>
   <tag></tag>
   <elementGuidId>766e7098-4d4d-46b6-8f6b-90d454c49d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genre_15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genre_15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0b7a7e9-764a-4ad8-bdd5-fa24ef394e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7b7264b6-6969-450d-8cc7-e90bfc295802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>470559a4-8013-4943-aa0e-5e2277ada40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genre[]</value>
      <webElementGuid>f8f2dd1f-bf71-4198-b16f-e2bb4307aadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genre_15</value>
      <webElementGuid>dbb5095a-0e43-4d92-ae2b-91e3090edc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>0ae97ee5-c468-43cf-8491-e71627e6ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genre_15&quot;)</value>
      <webElementGuid>011c9375-8a15-483e-b6f5-bd1d542b26dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genre_15']</value>
      <webElementGuid>e5902702-8750-45c3-aa38-fcd8963a990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/input</value>
      <webElementGuid>77296c51-98ad-4c52-b5ba-442d7c8651f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'genre[]' and @id = 'genre_15']</value>
      <webElementGuid>33575376-4866-4b87-8073-bb15f799f92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
