<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bch Hp</name>
   <tag></tag>
   <elementGuidId>749b4fa9-cf10-48ca-aa45-9e4dcde1588c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a2efe03-a8e3-491e-b3c6-961dbfa228d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>bfeff34f-9618-466d-b3cb-2526d3dd700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://truyenteen.me/the-loai/bach-hop</value>
      <webElementGuid>095d6bb4-2d7e-4464-8044-3411474a8881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bách Hợp</value>
      <webElementGuid>30786a50-a2b2-4486-ba43-26fa4deaf0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav m-auto&quot;]/li[@class=&quot;nav-item dropdown has-mega-menu mr-2&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;px-0 container container-md&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-md-4&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>ddb70079-72a4-40af-b855-d82862b072eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/a</value>
      <webElementGuid>9ea288d1-f4fc-4d79-b83c-bcda6cb565ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bách Hợp')]</value>
      <webElementGuid>0c5c145a-8a57-4f69-9235-7581c739b81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TruyenTeen'])[1]/following::a[2]</value>
      <webElementGuid>ff0b05d4-6ba7-460d-bf8c-01ae118dcc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cổ Đại'])[1]/preceding::a[1]</value>
      <webElementGuid>dd43fd56-cd2b-4ed7-9968-4d0f46330a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cung Đấu'])[1]/preceding::a[2]</value>
      <webElementGuid>fddaebb5-8f89-4f20-9218-ce66d4543e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bách Hợp']/parent::*</value>
      <webElementGuid>5494670b-da76-4422-bb84-f4bb9bcccdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://truyenteen.me/the-loai/bach-hop')]</value>
      <webElementGuid>1c5a6f79-24be-4bd3-bcb9-bbd157a301c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>7769779b-9ba7-4a21-bf18-ecc75b24bd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://truyenteen.me/the-loai/bach-hop' and (text() = 'Bách Hợp' or . = 'Bách Hợp')]</value>
      <webElementGuid>74637e0a-c1cf-4d20-b054-f77211a5b1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
